
# We fix the project name so DNS names are deterministic
# This in order to use nginx LB in full, instead of docker's dns round-robin strategy.
name: rundeck-cluster

services:
  nginx:
    image: nginx
    depends_on:
      rundeck:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - default
  web:
    image: strm/helloworld-http
    networks:
      - default
    ports:
      - 8000:80
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password
      - USER_NAME=admin
    volumes:
      - /path/to/openssh-server/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: heslo123
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432

volumes:
  logdata:
  pgdata:
